### ISSUE TITLE
as_shape no longer exported from pygeotif.geometry

### ISSUE THREAD

**Issue by mixtah** [cleder/czml#32]
```
from pygeoif.geometry import as_shape as asShape
```
Line 46 of czml.py attempts to import as_shape from pygeoif.geometry. Since the 1.0 release this isn't exported anymore leading to an import error when loading the package.

A quick solution would be to peg pygeoif to version 0.6.
I'm so far unsure what can be used in it's place, but updating the usage would be better in the long term.

**Comment by cleder** [comment]
version pegged it to 0.7, longer term is only relevant if somebody would like to take it over
